var rank_2005 = [
  {'book': '凉宫春日系列', 'auth': '谷川流', 'painter': '伊东杂音', 'ph': '角川Sneaker文库'},
  {'book': '戏言系列', 'auth': '西尾维新', 'painter': '竹', 'ph': '讲谈社Novels' },
  {'book': '恶魔同盟', 'auth': 'うえお久光', 'painter': '藤田香', 'ph': '电击文库' },
  {'book': '流血女神传', 'auth': '须贺しのぶ', 'painter': '船户明里', 'ph': 'Cobalt文库' },
  {'book': '永生之酒', 'auth': '成田良悟', 'painter': '榎波克己', 'ph': '电击文库' },
  {'book': '七姬物语', 'auth': '高野和', 'painter': '尾谷修', 'ph': '电击文库' },
  {'book': '天空之钟响彻惑星', 'auth': '渡濑草一郎', 'painter': '岩崎美奈子', 'ph': '电击文库' },
  {'book': '艾莉森', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '扑杀天使朵库萝	', 'auth': '小粥正木', 'painter': 'とりしも', 'ph': '电击文库' },
  {'book': '混沌军团', 'auth': '冲方丁', 'painter': '结贺理', 'ph': '富士见Fantasia文库' },
  {'book': '终焉的年代记', 'auth': '川上稔', 'painter': 'さとやす', 'ph': '电击文库' },
  {'book': '银盘万花筒', 'auth': '海原零', 'painter': '铃平ひろ', 'ph': '集英社Super Dash文库' },
  {'book': 'D Crackers', 'auth': '字野耕平', 'painter': '村崎久都', 'ph': '富士见书房' },
  {'book': '乐园的魔女们', 'auth': '树川 さとみ', 'painter': 'むっちりむうにい', 'ph': 'Cobalt文库' },
  {'book': '圣母在上', 'auth': '今野绪雪', 'painter': '响玲音', 'ph': 'Cobalt文库' },
  {'book': '仰望半月的夜空', 'auth': '桥本纺', 'painter': '山本启治', 'ph': '电击文库' },
  {'book': '全金属狂潮', 'auth': '贺东招二', 'painter': '四季童子', 'ph': '富士见Fantasia文库' },
  {'book': '罪人与龙共舞', 'auth': '浅井Labo', 'painter': '宫城', 'ph': '角川Sneaker文库' },
  {'book': '吉永家的石像怪', 'auth': '田口仙年堂', 'painter': '日向悠二', 'ph': 'Fami通文库' },
  {'book': '空之境界', 'auth': '奈须蘑菇', 'painter': 'TYPE-MOON', 'ph': '讲谈社Novels' }
];

var rank_2006 =[
  {'book': '戏言系列', 'auth': '西尾维新', 'painter': '竹', 'ph': '讲谈社Novels' },
  {'book': '奇诺之旅', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '糖果子弹', 'auth': '樱庭一树', 'painter': '	むー', 'ph': '富士见Fantasia文库' },
  {'book': '天空之钟响彻惑星', 'auth': '渡濑草一郎', 'painter': '岩崎美奈子', 'ph': '电击文库' },
  {'book': '终焉的年代记', 'auth': '川上稔', 'painter': 'さとやす', 'ph': '电击文库' },
  {'book': '凉宫春日系列', 'auth': '谷川流', 'painter': '伊东杂音', 'ph': '角川Sneaker文库' },
  {'book': '我们俩的田村同学', 'auth': '竹宫悠由子', 'painter': '泰', 'ph': '电击文库' },
  {'book': '罪人与龙共舞	', 'auth': '浅井Labo', 'painter': '宫城', 'ph': '角川Sneaker文库' },
  {'book': 'All You Need Is Kill', 'auth': '樱坂洋', 'painter': '安倍吉俊', 'ph': '集英社Super Dash文库' },
  {'book': '仰望半月的夜空', 'auth': '桥本纺', 'painter': '山本启治', 'ph': '电击文库' },
  {'book': '电波系彼女', 'auth': '片山宪太郎', 'painter': '山本大和', 'ph': '集英社Super Dash文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '全金属狂潮', 'auth': '贺东招二', 'painter': '四季童子', 'ph': '富士见Fantasia文库' },
  {'book': '今天开始做魔王', 'auth': '乔林知', 'painter': '松本手毬', 'ph': '角川Sneaker文库' },
  {'book': '灼眼的夏娜', 'auth': '高桥弥七郎', 'painter': '伊东杂音', 'ph': '电击文库' },
  {'book': 'Wizards brain', 'auth': '三枝零一', 'painter': '纯圭一', 'ph': '电击文库' },
  {'book': '不吉波普系列', 'auth': '上远野浩平', 'painter': '绪方刚志', 'ph': '电击文库' },
  {'book': '圣母在上', 'auth': '今野绪雪', 'painter': '响玲音', 'ph': '集英社Super Dash文库' },
  {'book': '9S', 'auth': '叶山透', 'painter': '山本大和', 'ph': '电击文库' },
  {'book': 'GOSICK', 'auth': '樱庭一树', 'painter': '武田日向', 'ph': '角川Sneaker文库' }
];

var rank_2007 = [
  {'book': '狼与香辛料', 'auth': '支仓冻砂', 'painter': '文仓十', 'ph': '电击文库' },
  {'book': '凉宫春日系列', 'auth': '谷川流', 'painter': '伊东杂音', 'ph': '角川Sneaker文库' },
  {'book': '戏言系列', 'auth': '西尾维新', 'painter': '竹', 'ph': '讲谈社Novels' },
  {'book': '仰望半月的夜空', 'auth': '桥本纺', 'painter': '山本启治', 'ph': '电击文库' },
  {'book': '奇诺之旅', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '龙与虎', 'auth': '竹宫悠由子', 'painter': '泰', 'ph': '电击文库' },
  {'book': '终焉的年代记', 'auth': '川上稔', 'painter': 'さとやす', 'ph': '电击文库' },
  {'book': '文学少女', 'auth': '野村美月', 'painter': '竹冈美穗', 'ph': 'Fami通文库' },
  {'book': '天空之钟响彻惑星', 'auth': '渡濑草一郎', 'painter': '岩崎美奈子', 'ph': '电击文库' },
  {'book': '某一天，炸弹从天而降', 'auth': '古桥秀之', 'painter': '绯贺ゆかり', 'ph': '电击文库' },
  {'book': '灼眼的夏娜', 'auth': '高桥弥七郎', 'painter': '伊东杂音', 'ph': '电击文库' },
  {'book': '零之使魔', 'auth': '山口升', 'painter': '兔冢英志', 'ph': 'MF文库J' },
  {'book': '黑血兄弟', 'auth': '字野耕平', 'painter': '草河游也', 'ph': '富士见Fantasia文库' },
  {'book': '魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '红', 'auth': '片山宪太郎', 'painter': '山本大和', 'ph': '集英社Super Dash文库' },
  {'book': '罪人与龙共舞	', 'auth': '浅井Labo', 'painter': '宫城', 'ph': '角川Sneaker文库' },
  {'book': '彩云国物语', 'auth': '雪乃纱衣', 'painter': '由罗绘里', 'ph': '雪乃纱衣' },
  {'book': '七姬物语', 'auth': '高野和', 'painter': '尾谷修', 'ph': '电击文库' },
  {'book': '出租魔法使', 'auth': '三田诚', 'painter': 'pako', 'ph': '角川Sneaker文库' }
]

var rank_2008 = [
  {'book': '全金属狂潮', 'auth': '贺东招二', 'painter': '四季童子', 'ph': '富士见Fantasia文库' },
  {'book': '凉宫春日系列', 'auth': '谷川流', 'painter': '伊东杂音', 'ph': '角川Sneaker文库' },
  {'book': '文学少女', 'auth': '野村美月', 'painter': '竹冈美穗', 'ph': 'Fami通文库' },
  {'book': '龙与虎', 'auth': '竹宫悠由子', 'painter': '泰', 'ph': '电击文库' },
  {'book': '狼与香辛料', 'auth': '支仓冻砂', 'painter': '文仓十', 'ph': '电击文库' },
  {'book': '奇诺之旅', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '角鸮与夜之王', 'auth': '红玉伊月', 'painter': '矶野宏夫', 'ph': '电击文库' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '黄昏色的咏使', 'auth': '细音启', 'painter': '竹冈美穗', 'ph': '富士见Fantasia文库' },
  {'book': '灼眼的夏娜', 'auth': '高桥弥七郎', 'painter': '伊东杂音', 'ph': '电击文库' },
  {'book': '物语系列', 'auth': '西尾维新', 'painter': 'VOFAN', 'ph': '讲谈社Novels' },
  {'book': '零之使魔', 'auth': '山口升', 'painter': '兔冢英志', 'ph': 'MF文库J' },
  {'book': '永生之酒', 'auth': '成田良悟', 'painter': '榎波克己', 'ph': '电击文库' },
  {'book': '虫之歌', 'auth': '岩井恭平', 'painter': 'LLO', 'ph': '角川Sneaker文库' },
  {'book': '魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '说谎的男孩与坏掉的女孩', 'auth': '入间人间', 'painter': '左', 'ph': '电击文库' },
  {'book': '人类衰退之后', 'auth': '田中罗密欧', 'painter': '山崎透', 'ph': 'Gagaga文库' },
  {'book': '黑血兄弟', 'auth': '字野耕平', 'painter': '草河游也', 'ph': '富士见Fantasia文库' },
  {'book': 'DDD', 'auth': '奈须蘑菇', 'painter': 'TYPE-MOON', 'ph': '讲谈社Novels' },
  {'book': 'Wizards brain', 'auth': '三枝零一', 'painter': '纯圭一', 'ph': '电击文库' }
]

var rank_2009 = [
  {'book': '文学少女', 'auth': '野村美月', 'painter': '竹冈美穗', 'ph': 'Fami通文库' },
  {'book': '龙与虎', 'auth': '竹宫悠由子', 'painter': '泰', 'ph': '电击文库' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '狼与香辛料', 'auth': '支仓冻砂', 'painter': '文仓十', 'ph': '电击文库' },
  {'book': '物语系列', 'auth': '西尾维新', 'painter': 'VOFAN', 'ph': '讲谈社Novels' },
  {'book': '碧阳学园学生会议事录', 'auth': '葵关南', 'painter': '狗神煌', 'ph': '富士见Fantasia文库' },
  {'book': '全金属狂潮', 'auth': '贺东招二', 'painter': '四季童子', 'ph': '富士见Fantasia文库' },
  {'book': '说谎的男孩与坏掉的女孩', 'auth': '入间人间', 'painter': '左', 'ph': '电击文库' },
  {'book': '对某个飞行员的追忆', 'auth': '犬村小六', 'painter': '森泽晴行', 'ph': 'Gagaga文库' },
  {'book': '黄昏色的咏使', 'auth': '细音启', 'painter': '竹冈美穗', 'ph': '富士见Fantasia文库' },
  {'book': '奇诺之旅', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '零之使魔', 'auth': '山口升', 'painter': '兔冢英志', 'ph': 'MF文库J' },
  {'book': 'AURA 魔龙院光牙最后的战斗', 'auth': '田中罗密欧', 'painter': 'mebae', 'ph': 'Gagaga文库' },
  {'book': '境界线上的地平线', 'auth': '川上稔', 'painter': 'さとやす', 'ph': '电击文库' },
  {'book': '离别的钢琴奏鸣曲', 'auth': '杉井光', 'painter': '植田亮', 'ph': '电击文库' },
  {'book': '灼眼的夏娜', 'auth': '高桥弥七郎', 'painter': '伊东杂音', 'ph': '电击文库' },
  {'book': '人类衰退之后', 'auth': '田中罗密欧', 'painter': '山崎透', 'ph': 'Gagaga文库' },
  {'book': '战斗！暴风少女！', 'auth': '佐佐原始绪', 'painter': '仓藤幸', 'ph': 'Fami通文库' },
  {'book': '便·当', 'auth': '朝浦', 'painter': '柴乃棹人', 'ph': '集英社Super Dash文库' }
]

var rank_2010 = [
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '物语系列', 'auth': '西尾维新', 'painter': 'VOFAN', 'ph': '讲谈社Novels' },
  {'book': '文学少女', 'auth': '野村美月', 'painter': '竹冈美穗', 'ph': 'Fami通文库' },
  {'book': '龙与虎', 'auth': '竹宫悠由子', 'painter': '泰', 'ph': '电击文库' },
  {'book': '碧阳学园学生会议事录', 'auth': '葵关南', 'painter': '狗神煌', 'ph': '富士见Fantasia文库' },
  {'book': '黄昏色的咏使', 'auth': '细音启', 'painter': '竹冈美穗', 'ph': '富士见Fantasia文库' },
  {'book': '说谎的男孩与坏掉的女孩', 'auth': '入间人间', 'painter': '左', 'ph': '电击文库' },
  {'book': '便·当', 'auth': '朝浦', 'painter': '柴乃棹人', 'ph': '集英社Super Dash文库' },
  {'book': '魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '苍穹的驱真', 'auth': '橘公司', 'painter': '森泽晴行', 'ph': '富士见Fantasia文库' },
  {'book': '离别的钢琴奏鸣曲', 'auth': '杉井光', 'painter': '植田亮', 'ph': '电击文库' },
  {'book': '我的妹妹哪有这么可爱！', 'auth': '伏见司', 'painter': '神崎广', 'ph': '电击文库' },
  {'book': '神的记事本', 'auth': '杉井光', 'painter': '岸田梅尔', 'ph': '电击文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '萝球社！', 'auth': '苍山探', 'painter': 'Tinkle', 'ph': '电击文库' },
  {'book': '战斗城塞玛斯拉沃', 'auth': '林トモアキ', 'painter': '上田', 'ph': '富士见Fantasia文库' },
  {'book': '境界线上的地平线', 'auth': '川上稔', 'painter': 'さとやす', 'ph': '电击文库' },
  {'book': '电波女与青春男', 'auth': '入间人间', 'painter': 'Buriki', 'ph': '电击文库' },
  {'book': '狼与香辛料', 'auth': '支仓冻砂', 'painter': '文仓十', 'ph': '电击文库' },
  {'book': '黑血兄弟', 'auth': '字野耕平', 'painter': '草河游也', 'ph': '富士见Fantasia文库' }
]

var rank_2011 = [
  {'book': '魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '我的朋友很少', 'auth': '平坂读', 'painter': 'Buriki', 'ph': 'MF文库J' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '便·当', 'auth': '朝浦', 'painter': '柴乃棹人', 'ph': '集英社Super Dash文库' },
  {'book': '文学少女', 'auth': '野村美月', 'painter': '竹冈美穗', 'ph': 'Fami通文库' },
  {'book': '碧阳学园学生会议事录', 'auth': '葵关南', 'painter': '狗神煌', 'ph': '富士见Fantasia文库' },
  {'book': '我的妹妹哪有这么可爱！', 'auth': '伏见司', 'painter': '神崎广', 'ph': '电击文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '神的记事本', 'auth': '杉井光', 'painter': '岸田梅尔', 'ph': '电击文库' },
  {'book': '全金属狂潮', 'auth': '贺东招二', 'painter': '四季童子', 'ph': '富士见Fantasia文库' },
  {'book': '物语系列', 'auth': '西尾维新', 'painter': 'VOFAN', 'ph': '讲谈社Novels' },
  {'book': '电波女与青春男', 'auth': '入间人间', 'painter': 'Buriki', 'ph': '电击文库' },
  {'book': '心灵链环', 'auth': '庵田定夏', 'painter': '白身鱼', 'ph': 'Fami通文库' },
  {'book': '说谎的男孩与坏掉的女孩', 'auth': '入间人间', 'painter': '左', 'ph': '电击文库' },
  {'book': '樱花庄的宠物女孩', 'auth': '鸭志田一', 'painter': '沟口凯吉', 'ph': '电击文库' },
  {'book': '献给某飞行员的恋歌', 'auth': '犬村小六', 'painter': '森泽晴行', 'ph': 'Gagaga文库' },
  {'book': '离别的钢琴奏鸣曲', 'auth': '杉井光', 'painter': '植田亮', 'ph': '电击文库' },
  {'book': '萝球社！', 'auth': '苍山探', 'painter': 'Tinkle', 'ph': '电击文库' },
  {'book': '灼眼的夏娜', 'auth': '高桥弥七郎', 'painter': '伊东杂音', 'ph': '电击文库' }
]

var rank_2012 = [
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '新约魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '便·当', 'auth': '朝浦', 'painter': '柴乃棹人', 'ph': '集英社Super Dash文库' },
  {'book': '圆环少女', 'auth': '长谷敏司', 'painter': '深游', 'ph': '角川Sneaker文库' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '我的朋友很少', 'auth': '平坂读', 'painter': 'Buriki', 'ph': 'MF文库J' },
  {'book': '超自然异象研究社', 'auth': '耳目口司', 'painter': 'まごまご', 'ph': '角川Sneaker文库' },
  {'book': '凉宫春日系列', 'auth': '谷川流', 'painter': '伊东杂音', 'ph': '角川Sneaker文库' },
  {'book': 'IDOLISING 偶像擂台！', 'auth': '広沢サカキ', 'painter': 'CUTEG', 'ph': '电击文库' },
  {'book': '雨天的艾莉丝', 'auth': '松山刚', 'painter': 'HIRASATO', 'ph': '电击文库' },
  {'book': '我的妹妹哪有这么可爱！', 'auth': '伏见司', 'painter': '神崎广', 'ph': '电击文库' },
  {'book': '心灵链环', 'auth': '庵田定夏', 'painter': '白身鱼', 'ph': 'Fami通文库' },
  {'book': '放学后的悠闲时光', 'auth': '比嘉智康', 'painter': 'すばち', 'ph': 'MF文库J' },
  {'book': '神的记事本', 'auth': '杉井光', 'painter': '岸田梅尔', 'ph': '电击文库' },
  {'book': '我的青春恋爱喜剧果然有问题', 'auth': '渡航', 'painter': 'Ponkan⑧', 'ph': 'Gagaga文库' },
  {'book': '变态王子与不笑猫', 'auth': '相乐总', 'painter': '监督', 'ph': 'MF文库J' },
  {'book': '金色时光', 'auth': '竹宫悠由子', 'painter': '驹都英二', 'ph': '电击文库' },
  {'book': '狼与香辛料', 'auth': '支仓冻砂', 'painter': '文仓十', 'ph': '电击文库' },
  {'book': '奇诺之旅', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '羽月莉音的帝国', 'auth': '至道流星', 'painter': '二之膳', 'ph': 'Gagaga文库' }
]

var rank_2013 = [
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '新约魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '六花之勇者', 'auth': '山形石雄', 'painter': '宫城', 'ph': '集英社Super Dash文库' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '我的妹妹哪有这么可爱！', 'auth': '伏见司', 'painter': '神崎广', 'ph': '电击文库' },
  {'book': '我的青春恋爱喜剧果然有问题', 'auth': '渡航', 'painter': 'Ponkan⑧', 'ph': 'Gagaga文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '东云侑子热爱短篇小说', 'auth': '森桥宾果', 'painter': 'Nardack', 'ph': 'Fami通文库' },
  {'book': '咲良田重置', 'auth': '河野裕', 'painter': '椎名优', 'ph': '角川Sneaker文库' },
  {'book': '境界线上的地平线', 'auth': '川上稔', 'painter': 'さとやす', 'ph': '电击文库' },
  {'book': '加速世界', 'auth': '川原砾', 'painter': 'HIMA', 'ph': '电击文库' },
  {'book': '魔法科高中的劣等生', 'auth': '佐岛勤', 'painter': '石田可奈', 'ph': '电击文库' },
  {'book': '发条精灵战记天镜的极北之星', 'auth': '宇野朴人', 'painter': 'さんば挿', 'ph': '电击文库' },
  {'book': '便·当', 'auth': '朝浦', 'painter': '柴乃棹人', 'ph': '集英社Super Dash文库' },
  {'book': '心灵链环', 'auth': '庵田定夏', 'painter': '白身鱼', 'ph': 'Fami通文库' },
  {'book': 'NO GAME NO LIFE游戏人生', 'auth': '榎宫佑', 'painter': '榎宫佑', 'ph': 'MF文库J' },
  {'book': '我的朋友很少', 'auth': '平坂读', 'painter': 'Buriki', 'ph': 'MF文库J' },
  {'book': '奇诺之旅', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '碧阳学园学生会议事录', 'auth': '葵关南', 'painter': '狗神煌', 'ph': '富士见Fantasia文库' },
  {'book': '农林', 'auth': '白鸟士郎', 'painter': '切符', 'ph': 'GA文库' }
]

var rank_2014 = [
  {'book': '我的青春恋爱喜剧果然有问题', 'auth': '渡航', 'painter': 'Ponkan⑧', 'ph': 'Gagaga文库' },
  {'book': '发条精灵战记天镜的极北之星', 'auth': '宇野朴人', 'painter': 'さんば挿', 'ph': '电击文库' },
  {'book': '新约魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '在地下城寻求邂逅是否搞错了什么', 'auth': '大森藤之', 'painter': '安田典生', 'ph': 'GA文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '打工吧！魔王大人', 'auth': '和原聪司', 'painter': '029', 'ph': '电击文库' },
  {'book': '东京暗鸦', 'auth': '字野耕平', 'painter': '澄兵', 'ph': '富士见Fantasia文库' },
  {'book': '六花之勇者', 'auth': '山形石雄', 'painter': '宫城', 'ph': '集英社Super Dash文库' },
  {'book': '我的妹妹哪有这么可爱！', 'auth': '伏见司', 'painter': '神崎广', 'ph': '电击文库' },
  {'book': 'NO GAME NO LIFE游戏人生', 'auth': '榎宫佑', 'painter': '榎宫佑', 'ph': 'MF文库J' },
  {'book': '独创短编系列野崎窗剧场', 'auth': '野崎窗', 'painter': '森井しづき', 'ph': '电击文库' },
  {'book': '不起眼女主角培育法', 'auth': '丸户史明', 'painter': '深崎暮人', 'ph': '富士见Fantasia文库' },
  {'book': '时钟机关之星', 'auth': '榎宫佑、暇奈椿', 'painter': '茨乃', 'ph': '讲谈社Novels' },
  {'book': '吸血鬼·夏日', 'auth': '石川博品', 'painter': '切符', 'ph': 'Fami通文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '霸剑的皇姬阿尔缇娜', 'auth': '村崎幸也', 'painter': 'himesuz', 'ph': 'Fami通文库' },
  {'book': 'EscApe SpeEd', 'auth': '九冈望', 'painter': '吟', 'ph': '电击文库' },
  {'book': '魔法科高中的劣等生', 'auth': '佐岛勤', 'painter': '石田可奈', 'ph': '电击文库' },
  {'book': '光在地球之时……', 'auth': '野村美月', 'painter': '竹冈美穗', 'ph': 'Fami通文库' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' }
]

var rank_2015 = [
  {'book': '我的青春恋爱喜剧果然有问题', 'auth': '渡航', 'painter': 'Ponkan⑧', 'ph': 'Gagaga文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': 'NO GAME NO LIFE游戏人生', 'auth': '榎宫佑', 'painter': '榎宫佑', 'ph': 'MF文库J' },
  {'book': '新约魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '后宫乐园球场', 'auth': '石川博品', 'painter': 'wingheart', 'ph': '集英社Super Dash文库' },
  {'book': '无尽深海的索拉利斯', 'auth': 'らきるち', 'painter': 'あさぎり', 'ph': 'MF文库J' },
  {'book': 'EscApe SpeEd', 'auth': '九冈望', 'painter': '吟', 'ph': '电击文库' },
  {'book': '与某飞行员的誓约', 'auth': '犬村小六', 'painter': '森泽晴行', 'ph': 'Gagaga文库' },
  {'book': '这个恋爱与那个未来', 'auth': '森桥宝果', 'painter': 'Nardack', 'ph': 'Fami通文库' },
  {'book': '发条精灵战记天镜的极北之星', 'auth': '宇野朴人', 'painter': 'さんば挿', 'ph': '电击文库' },
  {'book': '在地下城寻求邂逅是否搞错了什么', 'auth': '大森藤之', 'painter': '安田典生', 'ph': 'GA文库' },
  {'book': '美丽四重奏', 'auth': '游步新梦', 'painter': 'DSマイル', 'ph': 'OVERLAP文库' },
  {'book': '魔法科高中的劣等生', 'auth': '佐岛勤', 'painter': '石田可奈', 'ph': '电击文库' },
  {'book': '不起眼女主角培育法', 'auth': '丸户史明', 'painter': '深崎暮人', 'ph': '富士见Fantasia文库' },
  {'book': '身为男高中生兼当红轻小说作家的我', 'auth': '时雨泽惠一', 'painter': '黑星红白', 'ph': '电击文库' },
  {'book': '笨蛋、测验、召唤兽', 'auth': '井上坚二', 'painter': '叶贺维', 'ph': 'Fami通文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '东池袋的流浪猫', 'auth': '杉井光', 'painter': 'くろでこ', 'ph': '电击文库' },
  {'book': '灰与幻想的格林姆迦尔', 'auth': '十文字青', 'painter': '白井锐利', 'ph': 'OVERLAP文库' },
  {'book': '人类衰退之后', 'auth': '田中罗密欧', 'painter': '山崎透', 'ph': 'Gagaga文库' }
]

var rank_2016 = [
  {'book': '我的青春恋爱喜剧果然有问题', 'auth': '渡航', 'painter': 'Ponkan⑧', 'ph': 'Gagaga文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '发条精灵战记天镜的极北之星', 'auth': '宇野朴人', 'painter': 'さんば挿', 'ph': '电击文库' },
  {'book': '艾露恩末码', 'auth': '东龙乃助', 'painter': '东龙乃助', 'ph': 'MF文库J' },
  {'book': '末日之际有没有空呢？可以来拯救吗？', 'auth': '枯野瑛', 'painter': 'ue', 'ph': '角川Sneaker文库' },
  {'book': 'NO GAME NO LIFE游戏人生', 'auth': '榎宫佑', 'painter': '榎宫佑', 'ph': 'MF文库J' },
  {'book': '新约魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '在地下城寻求邂逅是否搞错了什么', 'auth': '大森藤之', 'painter': '安田典生', 'ph': 'GA文库' },
  {'book': '不起眼女主角培育法', 'auth': '丸户史明', 'painter': '深崎暮人', 'ph': '富士见Fantasia文库' },
  {'book': 'EscApe SpeEd', 'auth': '九冈望', 'painter': '吟', 'ph': '电击文库' },
  {'book': '魔法科高中的劣等生', 'auth': '佐岛勤', 'painter': '石田可奈', 'ph': '电击文库' },
  {'book': '我的朋友很少', 'auth': '平坂读', 'painter': 'Buriki', 'ph': 'MF文库J' },
  {'book': 'GAMERS!', 'auth': '葵关南', 'painter': '仙人掌', 'ph': '富士见Fantasia文库' },
  {'book': '这个恋爱与、那个未来', 'auth': '森桥宾果', 'painter': 'Nardac', 'ph': 'Fami通文库' },
  {'book': '六花之勇者', 'auth': '山形石雄', 'painter': '宫城', 'ph': '集英社Super Dash文库' },
  {'book': '无头骑士异闻录', 'auth': '成田良悟', 'painter': '安田典生', 'ph': '电击文库' },
  {'book': '预读男子与投稿女子', 'auth': '野村美月', 'painter': 'えいひ', 'ph': 'Fami通文库' },
  {'book': '战斗面包师与机械看板娘', 'auth': 'SOW', 'painter': 'ザザ', 'ph': 'HJ文库' }
]

var rank_2017 = [
  {'book': '龙王的工作！', 'auth': '白鸟士郎', 'painter': 'Shirabi', 'ph': 'GA文库' },
  {'book': 'Re：从零开始的异世界生活', 'auth': '长月达平', 'painter': '大冢真一郎', 'ph': 'MF文库J' },
  {'book': '新约魔法禁书目录', 'auth': '镰池和马', 'painter': '灰村清孝', 'ph': '电击文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': '哥布林杀手', 'auth': '蜗牛くも', 'painter': '神奈月升', 'ph': 'GA文库' },
  {'book': 'Melody Lyrik Idol Magik', 'auth': '石川博品', 'painter': 'POO', 'ph': 'DX文库' },
  {'book': 'GAMERS!', 'auth': '葵关南', 'painter': '仙人掌', 'ph': '富士见Fantasia文库' },
  {'book': '弱角友崎同学', 'auth': '屋久ユウキ', 'painter': 'フライ', 'ph': 'GAGAGA文库' },
  {'book': '为美好的世界献上祝福！', 'auth': '晓なつめ', 'painter': '三岛黑音', 'ph': 'Sneaker文库' },
  {'book': '这个恋爱与、那个未来', 'auth': '森桥宾果', 'painter': 'Nardac', 'ph': 'Fami通文库' },
  {'book': '灰与幻想的格林姆迦尔', 'auth': '十文字青', 'painter': '白井锐利', 'ph': 'OVERLAP文库' },
  {'book': '如果有妹妹就好了。', 'auth': '平坂读', 'painter': 'kantoku', 'ph': 'GAGAGA文库' },
  {'book': '不起眼女主角培育法', 'auth': '丸户史明', 'painter': '深崎暮人', 'ph': '富士见Fantasia文库' },
  {'book': '青春期笨蛋不做兔女郎学姐的梦', 'auth': '鸭志田一', 'painter': '沟口凯吉', 'ph': '电击文库' },
  {'book': '十七岁的他们忽远忽近', 'auth': '久远侑', 'painter': '和遥キナ', 'ph': 'Fami通文库' },
  {'book': '与某飞行员的誓约', 'auth': '犬村小六', 'painter': '森泽晴行', 'ph': 'Gagaga文库' },
  {'book': '喜欢本大爷的竟然就你一个？', 'auth': '骆驼	', 'painter': 'Buriki', 'ph': '电击文库' },
  {'book': '在地下城寻求邂逅是否搞错了什么', 'auth': '大森藤之', 'painter': '安田典生', 'ph': 'GA文库' },
  {'book': '世界尽头的圣骑士', 'auth': '柳野かなた', 'painter': '轮くすさが', 'ph': 'Overlap文库' },
  {'book': '筺底のエルピス', 'auth': 'オキシタケヒコ	', 'painter': 'toi8', 'ph': 'GAGAGA文库' }
]

var rank_2018 = [
  {'book': '龙王的工作！', 'auth': '白鸟士郎', 'painter': 'Shirabi', 'ph': 'GA文库' },
  {'book': '86- Eighty Six -', 'auth': '安里アサト', 'painter': 'Shirabi', 'ph': '电击文库' },
  {'book': '无尽连锁', 'auth': '海道左近', 'painter': 'タイキ', 'ph': 'HJ文库' },
  {'book': '月とライカと吸血姫', 'auth': '牧野圭祐', 'painter': 'かれい', 'ph': 'GAGAGA文库' },
  {'book': '刀剑神域', 'auth': '川原砾', 'painter': 'abec', 'ph': '电击文库' },
  {'book': 'ぼくたちのリメイク', 'auth': '木绪なち', 'painter': 'えれっと', 'ph': 'MF文库J' },
  {'book': '弱角友崎同学', 'auth': '屋久ユウキ', 'painter': 'フライ', 'ph': 'GAGAGA文库' },
  {'book': 'GAMERS!', 'auth': '葵关南', 'painter': '仙人掌', 'ph': '富士见Fantasia文库' },
  {'book': '在地下城寻求邂逅是否搞错了什么', 'auth': '大森藤之', 'painter': '安田典生', 'ph': 'GA文库' },
  {'book': '如果有妹妹就好了。', 'auth': '平坂读', 'painter': 'kantoku', 'ph': 'GAGAGA文库' },
  {'book': 'やがて恋するヴィヴィ・レイン', 'auth': '犬村小六', 'painter': '岩崎美奈子	', 'ph': 'GAGAGA文库' },
  {'book': '为美好的世界献上祝福！', 'auth': '晓なつめ', 'painter': '三岛黑音', 'ph': 'Sneaker文库' },
  {'book': '精灵幻想记', 'auth': '北山结莉', 'painter': 'Riv', 'ph': 'HJ文库' },
  {'book': '世界尽头的圣骑士', 'auth': '柳野かなた', 'painter': '轮くすさが', 'ph': 'Overlap文库' },
  {'book': '始まりの魔法使い', 'auth': '石之宫カント', 'painter': 'タイキ', 'ph': 'ファルまろ' },
  {'book': 'Re：从零开始的异世界生活', 'auth': '长月达平', 'painter': '大冢真一郎', 'ph': 'MF文库J' },
  {'book': '筺底のエルピス', 'auth': 'オキシタケヒコ', 'painter': 'ブリキ', 'ph': 'GAGAGA文库' },
  {'book': '魔法科高中的劣等生', 'auth': '佐岛勤', 'painter': '石田可奈', 'ph': '电击文库' },
  {'book': '欢迎来到实力至上主义的教室', 'auth': '衣笠彰梧', 'painter': 'トモセシュンサク', 'ph': 'MF文库J' },
  {'book': '青春期笨蛋不做兔女郎学姐的梦', 'auth': '鸭志田一', 'painter': '沟口凯吉', 'ph': '电击文库' }

]
